language: java
script: ant clean; ant compile; ant package;
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: NgQBI901vNVMHrJ7ahM+vPfFQCvmMTAf/f+5jerQS/cNtlbM8qHx660lYQqO5Ll48CFsscM5gOftdFjgG1niR2M91qb5rIjCswau8Hd/ekgi1rwbWSIzAFPEJ8uk0gpr2u/wY/2kJT2j40y01vg8QweEXUqQ595JiIJxhd+qmUGV3EhWcF1VFL6JCp1qNXWnNSqbkPSKWC582i9BhSYkXclIvqOUBE3Ivz0n0cFX/28DnmiBwjAoV04nxXW+N8LWR/levSe/RinH3yW6CnkuSGGZb6mUIgqXkzev6HXeJlQ6ojzBPScfITHBtxW1FeaY8Ueas4uavP5ZkURNfrGBnck9kQWR32p75SNljPuwLQ2x0uBFxfeIniiB41CIRJerkeLaykWew1UItmCdJoa9Iqca5jyqVp1lgZx/a94r+uxq/5hYFqIxAA/EQN4PldmzXbBrHeqpOBBaVbVYhRZ/b0msXV3SDp6iw/5thkZxjcuyCHDf37qaXfxdV6hsuvN6qGvTToeNu1jrNGUAaqpmJIFYJs3rjhwUaAeRyh+X3MEGhHiYXLdEsBcF4U0nefxvBFLZQ6ZYo2JCO3Mi1JU9Et+omeU3IZ6TNwjT6v7dqtOp6mZ8WCm90+3a5GWH/fqdLCI8aQrJURsmYiyRv+dp4WAMubx15Y8+nUXedwtj1Yo=
  file: sticky-notes-installer.jar
  skip_cleanup: true
  on:
    tags: false
env:
  global:
    secure: NS1zJnKKiDXiJccKpfLMgvwVyGnrLdLFUq8ytFboaVgPpqWEQ1pQOOxldIdCiVtM9TsoUPv3zw5NdbBQhVpUop0Cn32y1NbP9HbNbiLj0jwgyidzhSwlzh9791tVLNBwsDMNhFzbEMvrmE4r5fPsz9BOS5PaR6cGvehHNNQln4QOeEoPN9F9XPteWbFvBNxCyEEa9EY7o267zqu3fxZvO2oxYwCSNG5TREhm0KIk2TT/6nhVFwOSshBv7weveAIfy/vTJM8kPj+wJULybOWLxno+/lm3zoDN4MBEgZASHIIY1FokW+hQJ/LGVCu0HIKvUDqXD5mpuE8GqlOYtrXaMn+bvo36RtL5W7npK8+Of8QoJrGvxcFwexuy16HuEEE9uQJNKpL5ywYQBFKJszeOVtXuPcZtQ20zp7kkdkCrYeiHZTC3yRbEaAx+La2rUpWLCyEwkFG7NhBRe1n+yXJg5wR+DxaFqrx9OUCl16iQgDxzpTSO39ocxEdN+CCDPXdU72OdLz7c1/wuMepPyxWcfz3GAZtAQA1MCMn+5XVlGfcDA6ePOUNYS8gEzE2BhUiQEaGGcvUTwJjg6MCHbAQzRc5k1jq+RHY2NZ2Td/8/GRItdn2XF4Dp64o8Id7EmJwbO24MSyHzA8vOmJZj5Qi8nqKI48PqZ0e0kayZNHqkx9g=
