language: java

script: 
  ant clean;
  ant compile;
  ant package;

deploy:
  provider: releases
  api_key:
    secure: "f10obxakLNAoxj0jNzHZoM54Tp4/hSvtOnyiG5Sb0JOBqRRHHyBXapG3JV61HaXKX1TtbYFt1iYaGqBLsc0PmsnoWQbByjsWbeZ5Sr92k28+ghKiHb+Rn3apFIzsBt7eHRlidv8n57JoZRWhafv+wWWl3UBJVD4vaHhjo779eLokpugb1242c8h9Jhj+VvOevflsVkSN4XWUCfSmUw9HPw9svIx//6IJV9wB3vaL0Nph0dQBIsChJbUifaQPfF7mJ2jf/FbUyhS+HoAnYXFlCUGXVbHJTh54Ad8/m3unBdP8PDLZ0r1R+ZCI+WY5fpfAlms1DGfYb3sHWRF3iG7NMlq1R1i/d5lRMZGYWADvxJf7fPCLcfPFhqerHTdhoGXTC/DCnACBXw894HXULhkv+H6uhnHc0Gmqad7FMzgchtT1OZUtSztuaAXALcB6fmiUuRfLn3uE70fWIcyp8WFUliBSCgTK/oN5T2nL6Lz131BTQwN8ZP8M9VfjJoc6/saGhyY3FrYG7+ZY1PATQV3vf13nBV/uBHpHiXMuOXdKOVMqdIW4O3qsrWfiSBONy/9DZ2MTwyjhgdbc3YZ68ThrdQrkxWCkRd7cFHUB29Lb9WFZwzCSJCAQLFY8pB2tbJg8fN+OdLwJvOw1Wj4wSa1n8Jq1XBBrUMmNGEHNRbaI7kE="
  file: sticky-notes-installer.jar
  skip_cleanup: true
  on:
    tags: false

